# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uuid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
