# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
    ]
